version: '3.9'

services:
  frontend:
    image: blockscout-frontend:local
    pull_policy: never
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
